### ISSUE TITLE
Help to customize code

### ISSUE THREAD

**Issue by damndemento** [jamesjmtaylor/esp32-ftms-server#4]
hi @jamesjmtaylor

I'm trying to use my schwinn ic7 bike magnet sensor - which fires once the wheel turns one round - to send ble-ftms data to a fitness app like zwift or rgt. I think your code can be helpful for my project, but I'm wondering why you declared an analog and a digital input pin. My plan was to connect sensor gnd to esp32 gnd and sensor signal to an input pin but unsure which to choose and why you've declared both.

I'm not familar with c++ / arduino programming but I think I can handle that if I understand your code a little better... I think I also have to recode the functions that calculate the kmh from rpm etc. but I think this shouldn't be too hard.

hope to get some explanation on that ;) thanks for sharing the code on github!

cheers
Dan

**Comment by damndemento** [comment]
since this is not an issue with your code I close it...

**Comment by jamesjmtaylor-dexcom** [comment]
Honestly I think the analog pin is a relic from when I was trying different input pins on my ESP32. I declared both so that I could alternate between them quickly as I swapped the wiring between them on my breadboard.  I'd suggest you do the same; try one and if the data doesn't make sense, try the other.

**Comment by damndemento** [comment]
;) thank you! I'll see what fits for my sensor...
